// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./src/components/BaseDialog/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    DetailInfo: typeof import('./src/components/DetailInfo/index.vue')['default']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    LoginValidator: typeof import('./src/components/LoginValidator/index.vue')['default']
    Popconfirm: typeof import('./src/components/popconfirm/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemePicker: typeof import('./src/components/ThemePicker/index.vue')['default']
    Tree: typeof import('./src/components/YxtContextMenu/Tree.vue')['default']
    TreeComp: typeof import('./src/components/TreeComp/index.vue')['default']
    YxtContextMenu: typeof import('./src/components/YxtContextMenu/index.vue')['default']
    YxtDescription: typeof import('./src/components/YxtDescription/index.vue')['default']
    YxtFloatButton: typeof import('./src/components/YxtFloatButton/index.vue')['default']
  }
}
